import{S as d,i}from"./assets/vendor-46aac873.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))r(e);new MutationObserver(e=>{for(const o of e)if(o.type==="childList")for(const s of o.addedNodes)s.tagName==="LINK"&&s.rel==="modulepreload"&&r(s)}).observe(document,{childList:!0,subtree:!0});function a(e){const o={};return e.integrity&&(o.integrity=e.integrity),e.referrerpolicy&&(o.referrerPolicy=e.referrerpolicy),e.crossorigin==="use-credentials"?o.credentials="include":e.crossorigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function r(e){if(e.ep)return;e.ep=!0;const o=a(e);fetch(e.href,o)}})();const u="41511602-ac1f0d864a13fd01c911f294b",m=document.querySelector(".search-form"),c=document.querySelector(".gallery"),f=document.querySelector(".search-input"),p=new d(".gallery a",{captionsData:"alt",captionDelay:250}),l=document.querySelector(".loader");l.style.display="none";m.addEventListener("submit",h);function h(n){n.preventDefault();const t=f.value.trim();if(!t){i.warning({title:"Warning!",message:"Please enter image name!",position:"topRight"});return}b(),l.style.display="block";const a=new URLSearchParams({key:u,q:t,image_type:"photo",orientation:"horizontal",safesearch:!0});fetch(`https://pixabay.com/api/?${a}`).then(r=>{if(l.style.display="none",!r.ok)throw new Error(r.status);return r.json()}).then(r=>{if(r.hits.length===0){i.error({message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"});return}g(r.hits),p.refresh()}).catch(r=>{console.error("Error fetching images:",r),i.error({message:"Failed to fetch images. Please try again later.",position:"topRight"})})}function g(n){const t=document.createDocumentFragment();n.forEach(a=>{const r=y(a);t.appendChild(r)}),c.appendChild(t)}function y(n){const t=document.createElement("div");return t.classList.add("card"),t.innerHTML=`
    <a class="gallery-link" href="${n.largeImageURL}">
        <img class="card-image" src="${n.webformatURL}" alt="${n.tags}" loading="lazy">
      </a>
      <div class="card-info">
        <p class="card-text"><b>Likes:</b> ${n.likes}</p>
        <p class="card-text"><b>Views:</b> ${n.views}</p>
        <p class="card-text"><b>Comments:</b> ${n.comments}</p>
        <p class="card-text"><b>Downloads:</b> ${n.downloads}</p>
      </div>
    `,t}function b(){c.innerHTML=""}
//# sourceMappingURL=commonHelpers.js.map
